# Generated by Django 6.0.4 on 2026-07-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_attendancecorrection'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrsettings',
            name='md_approval_required',
            field=models.BooleanField(default=True, help_text='When ON, all leave requests approved by HR must also be approved by the MD.', verbose_name='Enable MD Approval Requirement'),
        ),
        migrations.AddField(
            model_name='leave',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(default='Pending Team Leader Approval', max_length=50),
        ),
    ]
