# Generated by Django 6.0.4 on 2026-07-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_hrsettings_md_approval_required_leave_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancecorrection',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='correction_attachments/'),
        ),
        migrations.AddField(
            model_name='attendancecorrection',
            name='batch_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
