# Generated by Django 6.0.4 on 2026-07-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_attendancecorrection_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_person',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='gst_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='gst_percent',
            field=models.FloatField(default=18.0),
        ),
        migrations.AddField(
            model_name='service',
            name='service_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
