# Generated by Django 6.0.4 on 2026-07-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0016_invoice_due_date_invoice_paid_date_invoice_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_in_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
