# Generated by Django 6.0.4 on 2026-07-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0018_project_client_project_client_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='calculated_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='calculation_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_holiday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_sandwich_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_weekoff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='original_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='payroll_count_flag',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hrsettings',
            name='grace_time',
            field=models.IntegerField(default=15, help_text='Grace time allowed for late check-in before mark as late.', verbose_name='Grace Time (Minutes)'),
        ),
        migrations.AddField(
            model_name='hrsettings',
            name='half_day_working_hours',
            field=models.FloatField(default=4.5, help_text='Minimum working hours required to count as Half Day instead of Absent.', verbose_name='Half Day Working Hours'),
        ),
        migrations.AddField(
            model_name='hrsettings',
            name='late_mark_rules_enabled',
            field=models.BooleanField(default=True, verbose_name='Enable Late Mark Rules'),
        ),
        migrations.AddField(
            model_name='hrsettings',
            name='office_end_time',
            field=models.TimeField(default='18:30:00', verbose_name='Office End Time'),
        ),
        migrations.AddField(
            model_name='hrsettings',
            name='office_start_time',
            field=models.TimeField(default='09:30:00', verbose_name='Office Start Time'),
        ),
        migrations.AddField(
            model_name='hrsettings',
            name='weekly_off_days',
            field=models.CharField(default='5,6', help_text="Comma-separated weekday numbers (0=Monday, 6=Sunday). Default Saturday and Sunday: '5,6'.", max_length=50, verbose_name='Weekly Off Days'),
        ),
    ]
