# Generated by Django 5.2.3 on 2026-07-10 10:40

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0022_remove_task_end_date_remove_task_members_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='actual_completion_date',
            new_name='actual_submission_time',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='base_performance_score',
            new_name='performance_score',
        ),
        migrations.RemoveField(
            model_name='project',
            name='assigned_team',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_employee',
        ),
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='extension_status',
        ),
        migrations.RemoveField(
            model_name='taskreview',
            name='final_percentage',
        ),
        migrations.RemoveField(
            model_name='taskreview',
            name='hr_modifier',
        ),
        migrations.RemoveField(
            model_name='taskreview',
            name='hr_reviewer',
        ),
        migrations.RemoveField(
            model_name='taskreview',
            name='md_modifier',
        ),
        migrations.RemoveField(
            model_name='taskreview',
            name='md_reviewer',
        ),
        migrations.RemoveField(
            model_name='taskreview',
            name='status',
        ),
        migrations.RemoveField(
            model_name='taskreview',
            name='tl_code_score',
        ),
        migrations.RemoveField(
            model_name='taskreview',
            name='tl_communication_score',
        ),
        migrations.RemoveField(
            model_name='taskreview',
            name='tl_final_percentage',
        ),
        migrations.RemoveField(
            model_name='taskreview',
            name='tl_productivity_score',
        ),
        migrations.RemoveField(
            model_name='taskreview',
            name='tl_quality_score',
        ),
        migrations.RemoveField(
            model_name='taskreview',
            name='tl_reviewer',
        ),
        migrations.RemoveField(
            model_name='taskreview',
            name='tl_timeliness_score',
        ),
        migrations.RemoveField(
            model_name='team',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_teams',
            field=models.ManyToManyField(blank=True, related_name='projects', to='hr.team'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateField(default=datetime.date(2026, 7, 10)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='extended_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_extended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskreview',
            name='final_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskreview',
            name='hr_reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskreview',
            name='hr_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskreview',
            name='md_reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='md_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskreview',
            name='md_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskreview',
            name='review_status',
            field=models.CharField(choices=[('Pending TL', 'Pending TL'), ('Pending HR', 'Pending HR'), ('Pending MD', 'Pending MD'), ('Finalized', 'Finalized')], default='Pending TL', max_length=50),
        ),
        migrations.AddField(
            model_name='taskreview',
            name='tl_reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tl_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskreview',
            name='tl_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(default=datetime.date(2026, 7, 10)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Submitted', 'Submitted'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Need Changes', 'Need Changes')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='TaskAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('user_role', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='hr.task')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('requested_hours', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to='hr.task')),
            ],
        ),
        migrations.DeleteModel(
            name='TaskExtensionRequest',
        ),
    ]
