# Generated by Django 5.2.3 on 2026-07-13 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0023_rename_actual_completion_date_task_actual_submission_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consecutive_on_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='performance_score',
            field=models.IntegerField(default=100),
        ),
        migrations.CreateModel(
            name='ProjectEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tasks_assigned', models.IntegerField(default=0)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('on_time_completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('late_submission_count', models.IntegerField(default=0)),
                ('work_quality', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=20)),
                ('technical_skills', models.IntegerField(default=0)),
                ('communication', models.IntegerField(default=0)),
                ('teamwork', models.IntegerField(default=0)),
                ('problem_solving', models.IntegerField(default=0)),
                ('discipline', models.IntegerField(default=0)),
                ('attendance', models.IntegerField(default=0)),
                ('deadline_adherence', models.IntegerField(default=0)),
                ('overall_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('strengths', models.TextField(blank=True, null=True)),
                ('areas_for_improvement', models.TextField(blank=True, null=True)),
                ('final_recommendation', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Average', 'Average'), ('Needs Improvement', 'Needs Improvement')], max_length=50)),
                ('overall_comments', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending HR', 'Pending HR'), ('Approved', 'Approved'), ('Returned', 'Returned')], default='Pending HR', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_evaluations', to=settings.AUTH_USER_MODEL)),
                ('evaluated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_evaluations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='hr.project')),
            ],
        ),
    ]
