# Generated by Django 5.2.3 on 2026-07-13 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0024_user_consecutive_on_time_user_performance_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='consecutive_on_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='performance_score',
        ),
        migrations.DeleteModel(
            name='ProjectEvaluation',
        ),
    ]
