# Generated by Django 5.2.3 on 2026-07-16 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0025_remove_user_consecutive_on_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(limit_choices_to={'role': 'Employee'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskreview',
            name='hr_reviewed_by',
            field=models.ForeignKey(limit_choices_to={'role': 'HR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskreview',
            name='md_reviewed_by',
            field=models.ForeignKey(limit_choices_to={'role': 'MD'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='md_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskreview',
            name='tl_reviewed_by',
            field=models.ForeignKey(limit_choices_to={'role': 'TeamLead'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tl_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
