# Generated by Django 5.2.3 on 2026-07-17 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0026_alter_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskreview',
            name='manager_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskreview',
            name='manager_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskreview',
            name='manager_reviewed_by',
            field=models.ForeignKey(limit_choices_to={'role': 'Manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskreview',
            name='manager_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskreview',
            name='review_status',
            field=models.CharField(choices=[('Pending TL', 'Pending TL'), ('Pending Manager', 'Pending Manager'), ('Pending HR', 'Pending HR'), ('Pending MD', 'Pending MD'), ('Finalized', 'Finalized')], default='Pending TL', max_length=50),
        ),
        migrations.CreateModel(
            name='ProjectReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tl_remarks', models.TextField(blank=True, null=True)),
                ('tl_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('manager_remarks', models.TextField(blank=True, null=True)),
                ('manager_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('hr_remarks', models.TextField(blank=True, null=True)),
                ('hr_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('md_remarks', models.TextField(blank=True, null=True)),
                ('md_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_status', models.CharField(choices=[('Pending TL Submission', 'Pending TL Submission'), ('Pending Manager', 'Pending Manager'), ('Pending HR', 'Pending HR'), ('Pending MD', 'Pending MD'), ('Finalized', 'Finalized')], default='Pending TL Submission', max_length=50)),
                ('hr_reviewed_by', models.ForeignKey(limit_choices_to={'role': 'HR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_project_reviews', to=settings.AUTH_USER_MODEL)),
                ('manager_reviewed_by', models.ForeignKey(limit_choices_to={'role': 'Manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_project_reviews', to=settings.AUTH_USER_MODEL)),
                ('md_reviewed_by', models.ForeignKey(limit_choices_to={'role': 'MD'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='md_project_reviews', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='hr.project')),
                ('tl_reviewed_by', models.ForeignKey(limit_choices_to={'role': 'TeamLead'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tl_project_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
