# Generated by Django 5.2.3 on 2026-07-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0027_taskreview_manager_remarks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('Web Dev', 'Web Dev'), ('Marketing', 'Marketing'), ('Training', 'Training'), ('Design', 'Design'), ('Cloud', 'Cloud'), ('Other', 'Other')], default='Web Dev', max_length=50)),
                ('author', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField()),
                ('content', models.TextField(blank=True, help_text='Full article content (optional)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='public/blog/')),
                ('read_time', models.CharField(default='5 min read', max_length=30)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Public Blog Post',
                'verbose_name_plural': 'Public Blog Posts',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('job_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship'), ('Contract', 'Contract')], default='Full Time', max_length=30)),
                ('experience', models.CharField(default='1-3 Years', max_length=100)),
                ('location', models.CharField(default='KPHB, Hyderabad', max_length=200)),
                ('department', models.CharField(default='Engineering', max_length=100)),
                ('description', models.TextField()),
                ('skills', models.CharField(help_text='Comma-separated skills, e.g. React.js,Python,Django', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Public Job Opening',
                'verbose_name_plural': 'Public Job Openings',
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(default='Web', max_length=100)),
                ('technology_stack', models.CharField(blank=True, help_text='Comma-separated, e.g. React, Django, PostgreSQL', max_length=300)),
                ('description', models.TextField()),
                ('project_url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='public/portfolio/')),
                ('color', models.CharField(default='#0796fe', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Public Portfolio Item',
                'verbose_name_plural': 'Public Portfolio Items',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
