# Generated by Django 5.2.3 on 2026-07-21 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0029_addcarouselimages_adminaccount_clientlead_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublicBlog',
        ),
        migrations.DeleteModel(
            name='PublicJob',
        ),
        migrations.DeleteModel(
            name='PublicPortfolio',
        ),
    ]
