# Generated by Django 4.2.30 on 2026-07-04 09:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancy',
            name='vacancies',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
