# Generated by Django 5.2.3 on 2026-07-17 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_jobvacancy_vacancies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
