/**
 * Centralized Route Constants for YGR Global IT Services
 * Distinguishes Public Website, Website CMS, and HRMS Modules cleanly.
 */

export const ROUTES = {
  // ── PUBLIC WEBSITE ─────────────────────────────────────────────────
  HOME: '/',
  ABOUT: '/about',
  SERVICES: '/services',
  PORTFOLIO: '/portfolio',
  CAREERS: '/careers',
  BLOG: '/blog',
  BLOG_DETAIL: '/blog/:id',
  CONTACT: '/contact',
  CLIENT_REGISTRATION: '/client-registration',
  TEAM: '/team',
  GLOBAL_INTERNSHIPS: '/global-internships',
  INTERNSHIP_DETAIL: '/internships/:slug',
  VACANCIES: '/vacancies',
  REGISTER_INTERNSHIP: '/register-internship',

  // ── WEBSITE CMS ADMIN (CMS Management) ────────────────────────────
  ADMIN_CMS_DASHBOARD: '/admin/website/dashboard',
  ADMIN_CMS_PROJECTS: '/admin/website/projects',
  ADMIN_CMS_PROJECT_ADD: '/admin/website/projects/add',
  ADMIN_CMS_PROJECT_EDIT: '/admin/website/projects/edit/:id',
  ADMIN_CMS_BLOGS: '/admin/website/blogs',
  ADMIN_CMS_BLOG_ADD: '/admin/website/blogs/add',
  ADMIN_CMS_BLOG_EDIT: '/admin/website/blogs/edit/:id',
  ADMIN_CMS_TEAM: '/admin/website/team',
  ADMIN_CMS_TEAM_ADD: '/admin/website/team/add',
  ADMIN_CMS_TEAM_EDIT: '/admin/website/team/edit/:id',
  ADMIN_CMS_TESTIMONIALS: '/admin/website/testimonials',
  ADMIN_CMS_TESTIMONIAL_ADD: '/admin/website/testimonials/add',
  ADMIN_CMS_TESTIMONIAL_EDIT: '/admin/website/testimonials/edit/:id',
  ADMIN_CMS_CAROUSEL: '/admin/website/carousel',
  ADMIN_CMS_CAROUSEL_ADD: '/admin/website/carousel/add',
  ADMIN_CMS_CAROUSEL_EDIT: '/admin/website/carousel/edit/:id',

  // ── HRMS DASHBOARDS & MODULES ─────────────────────────────────────
  HRMS_LOGIN: '/login',
  HRMS_PORTAL: '/portal',
  HRMS_EMPLOYEE_DASHBOARD: '/employee-dashboard',
  HRMS_HR_DASHBOARD: '/hr-dashboard',
  HRMS_MANAGER_DASHBOARD: '/manager-dashboard',
  HRMS_TL_DASHBOARD: '/tl-dashboard',
  HRMS_MD_DASHBOARD: '/md-dashboard',
  HRMS_REGISTER: '/register',
  HRMS_EMPLOYEES: '/employee-list',
  HRMS_HR_LIST: '/hr-list',
  HRMS_MANAGER_LIST: '/manager-list',
  HRMS_TL_LIST: '/tl-list',
  HRMS_PROJECTS: '/project-dashboard',
  HRMS_TASKS: '/tasks',
  HRMS_ATTENDANCE: '/attendance',
  HRMS_ATTENDANCE_LIST: '/attendance-list',
  HRMS_MONTHLY_ATTENDANCE: '/monthly-attendance',
  HRMS_ATTENDANCE_CORRECT: '/attendance-correct',
  HRMS_ATTENDANCE_CORRECT_BULK: '/attendance-correct-bulk',
  HRMS_ATTENDANCE_APPROVALS: '/attendance-approvals',
  HRMS_LEAVE_STATUS: '/leave-status',
  HRMS_LEAVE_REQUESTS: '/leave-requests',
  HRMS_ALL_LEAVES: '/all-leaves',
  HRMS_HR_APPROVED_LEAVES: '/hr-approved-leaves',
  HRMS_MANAGER_APPROVED_LEAVES: '/manager-approved-leaves',
  HRMS_TL_APPROVED_LEAVES: '/tl-approved-leaves',
  HRMS_PAYSLIPS: '/payslips',
  HRMS_PAYROLL: '/finance/payroll',
  HRMS_INVOICES: '/finance/invoices',
  HRMS_CLIENT_CREATE: '/finance/clients/new',
  HRMS_SERVICE_CREATE: '/finance/services/new',
  HRMS_INVOICE_CREATE: '/finance/invoices/create',
  HRMS_SALARY_STRUCTURES: '/finance/salary-structures',
  HRMS_HOLIDAYS: '/holidays',
  HRMS_HOLIDAY_APPROVALS: '/holiday-approvals',
  HRMS_SETTINGS: '/settings',
  HRMS_QUESTIONS: '/questions',
  HRMS_PROFILE: '/profile',
  HRMS_MESSAGES: '/messages',
  HRMS_CALLS: '/calls',
  HRMS_EXAMS: '/exams'
};
